name: Trigger Gatsby Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Dispatch Gatsby build
        run: |
          curl -XPOST -u "${{ secrets.PAT_USERNAME}}:${{secrets.PAT_TOKEN}}" -H "Accept: application/vnd.github.everest-preview+json"  -H "Content-Type: application/json" https://api.github.com/repos/ny-a/blog2/dispatches --data '{"event_type": "build_application"}'

      - name: Dispatch Gridsome build
        run: |
          curl -XPOST -u "${{ secrets.PAT_USERNAME}}:${{secrets.PAT_TOKEN}}" -H "Accept: application/vnd.github.everest-preview+json"  -H "Content-Type: application/json" https://api.github.com/repos/ny-a/gridsome-blog/dispatches --data '{"event_type": "build_application"}'
